### ISSUE TITLE
[Bug] can't update via launcher

### ISSUE THREAD

**Issue by leminsc8er** [ampersoftware/Creators.TF-Community-Launcher#44]
**UI or Mechanical Bug?**
both

**Describe the bug**
after starting the app, the update avible info avible.
does not shoow yellow button.
cant update via launcher...

**Was there an error dialogue for this bug? If so please provide a screenshot/its contents here**
no

**To Reproduce**
start app

**Expected behavior**
1. start app
2. auto search for uptaes.
3. show update info
4.  no yellow button avible
5. can't update via launcher

**Launcher Logs**
```
[29-04-2021] [21:35:24T+02:00] -- [browser] -- [info]  -- Current launcher version: 0.2.2
[29-04-2021] [21:35:24T+02:00] -- [browser] -- [info]  -- Checking for updates
[29-04-2021] [21:35:24T+02:00] -- [browser] -- [info]  -- Checking for updates.
[29-04-2021] [21:35:24T+02:00] -- [browser] -- [info]  -- Basic System Information: [platform: win32, release: 10.0.19042, arch: x64, systemmem: 7.84 gb]
[29-04-2021] [21:35:24T+02:00] -- [browser] -- [info]  -- Launcher was opened/finished initialization.
[29-04-2021] [21:35:24T+02:00] -- [browser] -- [info]  -- Loaded pre existing config
[29-04-2021] [21:35:25T+02:00] -- [browser] -- [info]  -- Checking for modlist updates
[29-04-2021] [21:35:25T+02:00] -- [browser] -- [info]  -- Trying to get mod list from: https://fastdl.creators.tf/launcher/mods.json
[29-04-2021] [21:35:25T+02:00] -- [browser] -- [info]  -- Trying to get mod list from: https://raw.githubusercontent.com/ampersoftware/Creators.TF-Community-Launcher/master/internal/mods.json
[29-04-2021] [21:35:25T+02:00] -- [browser] -- [error] -- Failed to parse json in TryGetModList request for https://fastdl.creators.tf/launcher/mods.json, error: SyntaxError: Unexpected token < in JSON at position 0
[29-04-2021] [21:35:25T+02:00] -- [browser] -- [info]  -- Local mod list version: 1.34, Remote mod list version: 1.34.
[29-04-2021] [21:35:25T+02:00] -- [browser] -- [verbose] -- Latest mod list was sent to renderer
[29-04-2021] [21:35:25T+02:00] -- [browser] -- [error] -- Error: Error: Cannot find latest.yml in the latest release artifacts (https://github.com/ampersoftware/Creators.TF-Community-Launcher/releases/download/v0.2.3/latest.yml): HttpError: 404 
"method: GET url: https://github.com/ampersoftware/Creators.TF-Community-Launcher/releases/download/v0.2.3/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Thu, 29 Apr 2021 19:34:19 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "F2CD:3827:5202312:54DF14E:608B0A7D"
}
    at createHttpError (C:\Program Files\Creators.TF Launcher\Creators.TF Community Launcher\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (C:\Program Files\Creators.TF Launcher\Creators.TF Community Launcher\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:169:14)
    at ClientRequest.<anonymous> (C:\Program Files\Creators.TF Launcher\Creators.TF Community Launcher\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
    at newError (C:\Program Files\Creators.TF Launcher\Creators.TF Community Launcher\resources\app.asar\node_modules\builder-util-runtime\out\index.js:212:17)
    at GitHubProvider.getLatestVersion (C:\Program Files\Creators.TF Launcher\Creators.TF Community Launcher\resources\app.asar\node_modules\electron-updater\out\providers\GitHubProvider.js:135:50)
    at async NsisUpdater.getUpdateInfoAndProvider (C:\Program Files\Creators.TF Launcher\Creators.TF Community Launcher\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:498:13)
    at async NsisUpdater.doCheckForUpdates (C:\Program Files\Creators.TF Launcher\Creators.TF Community Launcher\resources\app.asar\node_modules\electron-updater\out\AppUpdater.js:514:20)
[29-04-2021] [21:35:25T+02:00] -- [browser] -- [error] -- Error in auto-updater: Error: Cannot find latest.yml in the latest release artifacts (https://github.com/ampersoftware/Creators.TF-Community-Launcher/releases/download/v0.2.3/latest.yml): HttpError: 404 
"method: GET url: https://github.com/ampersoftware/Creators.TF-Community-Launcher/releases/download/v0.2.3/latest.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Thu, 29 Apr 2021 19:34:19 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, Accept-Encoding, Accept, X-Requested-With",
  "permissions-policy": "interest-cohort=()",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "expect-ct": "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\"",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "F2CD:3827:5202312:54DF14E:608B0A7D"
}
    at createHttpError (C:\Program Files\Creators.TF Launcher\Creators.TF Community Launcher\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (C:\Program Files\Creators.TF Launcher\Creators.TF Community Launcher\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:169:14)
    at ClientRequest.<anonymous> (C:\Program Files\Creators.TF Launcher\Creators.TF Community Launcher\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6816)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
[29-04-2021] [21:35:35T+02:00] -- [browser] -- [info]  -- Loading Patch Notes window...
[29-04-2021] [21:35:39T+02:00] -- [browser] -- [info]  -- Launcher was closed.

```

**Screenshots**
no need it.

**Desktop (please complete the following information):**
 - OS: Win10
 - Launcher v0.2.2

**Additional context**
old bug...

**Comment by jota11** [comment]
This happens because we moved away from the `v` prefixed tag names, and the version you are using (v0.2.2) is still trying to get `latest.yml` with a `v` prefixed tag (v0.2.3).

> "...Error: Cannot find latest.yml in the latest release artifacts (https://github.com/ampersoftware/Creators.TF-Community-Launcher/releases/download/v0.2.3/latest.yml):..."

This works [https://github.com/ampersoftware/Creators.TF-Community-Launcher/releases/download/0.2.3/latest.yml](https://github.com/ampersoftware/Creators.TF-Community-Launcher/releases/download/0.2.3/latest.yml)
This doesn't [https://github.com/ampersoftware/Creators.TF-Community-Launcher/releases/download/v0.2.3/latest.yml](https://github.com/ampersoftware/Creators.TF-Community-Launcher/releases/download/v0.2.3/latest.yml)

The only fix for this is to manually download and install the .exe from the [latest release](https://github.com/ampersoftware/Creators.TF-Community-Launcher/releases/tag/0.2.3).
Feel free to reopen this issue if it happens again in the next update.
